popsim-consortium/demes-spec

demes-specification.yaml

Combine asymmetric and symmetric migration.

---

.github/workflows/tests.yml
requirements.txt

Some lightweight CI to run tests on the reference implementation and the schema.
I don't think it's worth bothering with linting/black in CI, we're not expecting this code to change much.

Add unit tests to CI

---

examples/zigzag.resolved.json
examples/zigzag.yaml

Fix Zigzag population sizes.

---

demes-specification.yaml
examples/bottleneck.resolved.json
examples/bottleneck.yaml
examples/browning_america.resolved.json
examples/cloning_example.resolved.json
examples/defaults_asymmetric_migration_changing_rate.resolved.json
examples/defaults_deme_ancestors.resolved.json
examples/defaults_deme_ancestors.yaml
examples/defaults_deme_many_epochs_global.resolved.json
examples/defaults_deme_many_epochs_global.yaml
examples/defaults_deme_many_epochs_local.resolved.json
examples/defaults_deme_many_epochs_local.yaml
examples/defaults_deme_many_epochs_overrides.resolved.json
examples/defaults_deme_many_epochs_overrides.yaml
examples/defaults_migration_properties.resolved.json
examples/defaults_pulse_properties.resolved.json
examples/defaults_symmetric_migration_changing_rate.resolved.json
examples/gutenkunst_ooa.resolved.json
examples/jacobs_papuans.resolved.json
examples/line_topology.resolved.json
examples/minimal.resolved.json
examples/offshoots.resolved.json
examples/stepping_stone_model.resolved.json
examples/zigzag.resolved.json
reference_implementation/parser.py
reference_implementation/tests.py

Enforce deme start times are inf for root demes.

---

examples/jacobs_papuans.resolved.json
examples/jacobs_papuans.yaml

Follows from:
https://github.com/popsim-consortium/demes-python/pull/241

Fix Jacobs et al. model.

---

docs/introduction.md

Add list of related software.

---

docs/_config.yml

Fix substitutions in the tutorial.

---

docs/specification.md
requirements.txt

Work in progress to break up the document structure into something more manageable.
I've split things up into
- Population genetics model
- Machine data model 
- Human data model
Hopefully this structure is good enough for us to start filling in some gaps in their final form - we can review the terminology and overall structure later, but let's try and get some content in.
Related: #86

Update document structure.

---

docs/specification.md

first pass at getting the pop gen model filled in in the spec docs.

pop gen model in spec

---

.gitignore
demes-fully-qualified-specification.yaml
demes-specification.yaml
reference_implementation/tests.py
requirements.txt
tests.py

Closes #97.
---
This fails immediately. I think it's becase we have infinity in the schema, which is not really valid JSON.

Add subschema test.

---

docs/specification.md
examples/bottleneck.resolved.json
examples/browning_america.resolved.json
examples/cloning_example.resolved.json
examples/defaults_asymmetric_migration_changing_rate.resolved.json
examples/defaults_deme_ancestors.resolved.json
examples/defaults_deme_many_epochs_global.resolved.json
examples/defaults_deme_many_epochs_local.resolved.json
examples/defaults_deme_many_epochs_overrides.resolved.json
examples/defaults_migration_properties.resolved.json
examples/defaults_pulse_properties.resolved.json
examples/defaults_symmetric_migration_changing_rate.resolved.json
examples/gutenkunst_ooa.resolved.json
examples/jacobs_papuans.resolved.json
examples/line_topology.resolved.json
examples/minimal.resolved.json
examples/offshoots.resolved.json
examples/stepping_stone_model.resolved.json
examples/zigzag.resolved.json
reference_implementation/parser.py
reference_implementation/tests.py
test-cases/valid/infinity_01.yaml
test-cases/valid/infinity_02.yaml
test-cases/valid/infinity_03.yaml
test-cases/valid/infinity_04.yaml
test-cases/valid/infinity_05.yaml
test-cases/valid/infinity_06.yaml
test-cases/valid/infinity_07.yaml
test-cases/valid/infinity_08.yaml

Use/test/document string "Infinity".

---

demes-fully-qualified-specification.yaml
demes-specification.yaml
examples/bottleneck.resolved.json
examples/browning_america.resolved.json
examples/cloning_example.resolved.json
examples/defaults_asymmetric_migration_changing_rate.resolved.json
examples/defaults_deme_ancestors.resolved.json
examples/defaults_deme_many_epochs_global.resolved.json
examples/defaults_deme_many_epochs_local.resolved.json
examples/defaults_deme_many_epochs_overrides.resolved.json
examples/defaults_migration_properties.resolved.json
examples/defaults_pulse_properties.resolved.json
examples/defaults_symmetric_migration_changing_rate.resolved.json
examples/gutenkunst_ooa.resolved.json
examples/jacobs_papuans.resolved.json
examples/line_topology.resolved.json
examples/minimal.resolved.json
examples/offshoots.resolved.json
examples/stepping_stone_model.resolved.json
examples/zigzag.resolved.json
reference_implementation/parser.py
reference_implementation/resolve_yaml.py
reference_implementation/tests.py
test-cases/invalid/bad_toplevel_metadata_01.yaml
test-cases/invalid/bad_toplevel_metadata_02.yaml
test-cases/invalid/bad_toplevel_metadata_03.yaml
test-cases/invalid/bad_toplevel_metadata_04.yaml
test-cases/valid/toplevel_metadata_01.yaml

Closes #65.
---
A couple of small unrelated assertions snuck in here, because I fixed some mypy warnings.

Add toplevel metadata.

---

reference_implementation/parser.py
test-cases/invalid/incompatible_selfing_cloning_rates_01.yaml
test-cases/valid/selfing_cloning_01.yaml

We must still have 0 <= selfing_rate, cloning_rate <= 1.
Closes #109.

Allow selfing_rate + cloning_rate > 1

---

demes-fully-qualified-specification.yaml
demes-specification.yaml
tests.py

Update the migration schema definitions.

---

docs/specification.md
reference_implementation/parser.py

s/deme ID/deme name/

---

reference_implementation/parser.py
test-cases/invalid/bad_pulses_20.yaml
test-cases/invalid/bad_pulses_21.yaml
test-cases/invalid/bad_pulses_22.yaml
test-cases/invalid/bad_toplevel_defaults_pulse_08.yaml
test-cases/invalid/bad_toplevel_defaults_pulse_09.yaml
test-cases/invalid/bad_toplevel_defaults_pulse_10.yaml
test-cases/invalid/bad_toplevel_defaults_pulse_11.yaml
test-cases/invalid/bad_toplevel_defaults_pulse_12.yaml
test-cases/invalid/bad_toplevel_defaults_pulse_13.yaml
test-cases/invalid/bad_toplevel_defaults_pulse_14.yaml
test-cases/invalid/bad_toplevel_defaults_pulse_15.yaml
test-cases/invalid/bad_toplevel_defaults_pulse_19.yaml
test-cases/invalid/bad_toplevel_defaults_pulse_20.yaml
test-cases/invalid/bad_toplevel_defaults_pulse_21.yaml
test-cases/invalid/bad_toplevel_defaults_pulse_22.yaml

These were missed following the source/proportion -> sources/proportions
conversion.

More test-cases for pulse sources/proportions.

---

docs/_config.yml
docs/specification.md
docs/tutorial.md
reference_implementation/parser.py

Some basic text for the HDM defaults section. I think this is probably enough: this is to teach people how to use it, just to explain to parser developers how it should be implemented. The combination of the schema and reference implementation is pretty thorough, so I think we don't have to do so much here.

HDM defaults spec

---

docs/specification.md

Here's a start on resolution - any thoughts @grahamgower?

Outline text for resolution

---

docs/specification.md

More HDM text. How to resolve sizes.

---

docs/specification.md

Resolution of migrations in HDM section of spec.

---

docs/specification.md

Closes #37.
Closes #91.
Also removes some text that applies to the HDM, not the MDM.

MDM spec text + cleanups

---

docs/specification.md

Add detailed description of pulse resolution.
The content comes from posts in #100.

Add example of resolving sequential pulses.

---

docs/specification.md

In response to one of the reviewers.
I wrote this "from memory", so it'd help to get a close look from @apragsdale, who wrote the first convert for fwdpy11.

Explain how to get a forward representation of time.

---

.github/workflows/docs.yml
docs/tutorial.md
requirements.txt

Also replaces the sphinx-panel bits with sphinx-design,
as sphinx-panel support has been removed from jupyter-book.

Bump versions for some deps
